site_name: "Chemistry Simulations"

theme:
    name: material
    custom_dir: mdocotion/
    sidebar_color: '#f1f5f9'
    logo: assets/logo.png
    features:
    - navigation.sections
    
plugins:
  - awesome-pages
  - section-index
  - macros:
      modules: [mkdocs_macros_mdocotion]
